title: hanshu.org
author:
  name: han shu
  email: tom.shuhan@gmail.com

site_name: hanshu.org
last_update: 2022-06

job: Bachelor's Degree Candidate
location: Xi'an, Shaanxi, China
work_pos1: Computer Science and Technology
work_pos: Northwestern Polytechnical University(NWPU)

icon_link: https://cdn.jsdelivr.net/gh/R1szW7xqoVdA/Vu-jewdLEw--f-_-/icon/icon-profile.ico
svg_link: https://cdn.jsdelivr.net/gh/R1szW7xqoVdA/Vu-jewdLEw--f-_-/icon/icon.svg

show_excerpts: false 

minima:
  date_format: "%b %-d, %Y"

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

markdown: kramdown
